export default {
  CLEAR_DATA: 'CLEAR_DATA',

  TOGGLE_THEME: 'TOGGLE_THEME',

  MODAL_SHOW: 'MODAL_SHOW',
  MODAL_HIDE: 'MODAL_HIDE',

  LOGOUT: 'LOGOUT',

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  TASK_GET: 'TASK_GET',
  TASK_GET_SUCCESS: 'TASK_GET_SUCCESS',
  TASK_GET_FAILED: 'TASK_GET_FAILED',

  TASK_CREATE: 'TASK_CREATE',
  TASK_CREATE_SUCCESS: 'TASK_CREATE_SUCCESS',
  TASK_CREATE_FAILED: 'TASK_CREATE_FAILED',

  TASK_DELETE: 'TASK_DELETE',
  TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',

  TASK_COMPLETE: 'TASK_COMPLETE',
  TASK_COMPLETE_SUCCESS: 'TASK_COMPLETE_SUCCESS',
  TASK_COMPLETE_FAILED: 'TASK_COMPLETE_FAILED',
};
